#!/bin/sh

if [ "X$CC" != "X" ] && echo "$CC" | grep '`' > /dev/null
then
    CC=
fi

if [ X$CC = X ]
then	CC=cc
	for p in `echo $PATH | sed 's/:/ /g'`
	do	if [ -f $p/arm-none-aebi-gcc ]
		then	CC=arm-none-aebi-gcc
		fi
	done
fi
echo $CC
