/*
 * Copyright (C) 2012, [Your Company Here] All Rights Reserved.
 * IT IS EXPECTED THAT THIS TEXT BE REPLACED WITH THE BOARD SOFTWARE
 * PROVIDER'S COPYRIGHT INFORMATION. THIS TEXT WILL BE DISPLAYED AT
 * THE TOP OF ALL SOURCE FILES GENERATED FOR THIS BOARD DESIGN.
*/

// File: usdhc_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.4.0.3
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "inc/iomux_config.h"
#include "inc/ltz_regsiomuxc.h"


void usdhc_iomux_config(int instance)
{
    switch (instance)
    {
        case 1:
            return usdhc1_iomux_config();

        case 2:
            return usdhc2_iomux_config();

        case 3:
            return usdhc3_iomux_config();

        case 4:
            return usdhc4_iomux_config();

        default: ;
    }
}
